# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Event:
  fields:
    default: name, private, live, permalink, password, occurred_on
    form: name, private, live, permalink, occurred_on, already_watermarked
  order_by: 
  relationships: photo_shares, photo_uploads, photos
  filters: 
  search: name
  application: makeascene
  actions:
    edit: preview, view_public

Photo:
  fields:
    default: event, image, cover_photo
    form: event, image, cover_photo
  order_by: 
  relationships: event, photo_shares
  filters: 
  search: 
  application: makeascene

PhotoShare:
  fields:
    default: photo, facebook_uid, facebook_photo_url
    form: photo, facebook_uid, facebook_photo_url
  order_by: 
  relationships: photo
  filters: 
  search: 
  application: makeascene

PhotoUpload:
  fields:
    default: event_id, archive_file_name, event
    form: event, archive, event
  order_by: 
  relationships: event
  filters: 
  search: 
  application: makeascene

Contact:
  fields:
    default: name, phone, email, event_type, event_date, comments
  order_by:
  application: makeascene
