development:
  access_key_id: '01A0AGCYE9V8P8BJ7T02'
  secret_access_key: 'fVPcyE/vAWnL8xUXv0jwolGAfKsaEZAAzA9hRHna'
  bucket: 'makeascene.development'

production:
  access_key_id: '01A0AGCYE9V8P8BJ7T02'
  secret_access_key: 'fVPcyE/vAWnL8xUXv0jwolGAfKsaEZAAzA9hRHna'
  bucket: 'makeascene.production'

